### PR TITLE
#68: Added support of pages

### LINKED ISSUE #50: [FE] Fix elements selection
Element selection in attach file is not applicable on "inspect page"
[7.1-t05-fail-b.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4710582/7.1-t05-fail-b.pdf)

### LINKED ISSUE #59: [FE - Inspect Page] Application crash on inspect page
**File:** 
[Book catalog 3 with working image.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4710700/Book.catalog.3.with.working.image.pdf)

Steps to repoduce: 

1. Select WCAG 2.1 All profile
2. Open inspect page
3. Select page in dropdown list
4. Click to document overview

**Actual result:** App crash. "Cannot read property 'pageIndex' of undefined"

### LINKED ISSUE #67: Fix old context support

### LINKED ISSUE #68: Add support of Page for context with annotation

### PR DESCRIPTION
**Pull request by Resip10**
closes #68: Filtering out metadata and unrecognized checks;
closes #50 and closes #59 fixed as unrecognized;
closes #67

### CODE REVIEW

File: src/components/layouts/pages/inspect/pdfDocument/PdfDocument.js [hunk 1]
```diff
@@ -90,11 +91,23 @@ class PdfDocument extends React.PureComponent {
...
+        if (context.toLowerCase().match('metadata')) {
+            return 'metadata';
+        }
+
+        if (!context.match('pages\\[')) {
+            return -1;
+        }
+
+        return parseInt(context.split('pages[')[1].split(']')[0]) - 1; // -1 because index
+    }
```
Comment (KateOrient) [inline src/components/layouts/pages/inspect/pdfDocument/PdfDocument.js:109]: It seems function `getPageFromContext` can be moved to `pdfService.js`

File: src/components/layouts/pages/inspect/tree/Tree.js [hunk 2]
```diff
@@ -117,20 +121,26 @@ function RuleList({ ruleSummaries, expandedRule, selectedCheck, onRuleClick, onC
...
     });
 }
 
-function CheckList({ checks, selectedCheck, onCheckClick }) {
-    return checks.map(({ context }, index) => {
+function CheckList({ checks, selectedCheck, onCheckClick, errorsMap }) {
+    let checksSorted = sortChecksByPage(checks, errorsMap);
+    return checksSorted.map(({ context }, index) => {
         return (
             <ListItem
```
Comment (KateOrient) [inline src/components/layouts/pages/inspect/tree/Tree.js:145]: Clicking on Unrecognised context results in page scolling (in case when context is a path to `contentItem` without `mcid`).  So, `ListItem` with Unrecognised context should be disabled

File: src/components/layouts/pages/inspect/pdfDocument/PdfDocument.js [hunk 3]
```diff
@@ -90,11 +91,23 @@ class PdfDocument extends React.PureComponent {
 
                 objectOfErrors = { ...nextStepObject };
             });
-            return findAllMcid(objectOfErrors);
+            return findAllMcid(objectOfErrors, page);
```
Comment (KateOrient) [inline src/components/layouts/pages/inspect/pdfDocument/PdfDocument.js:94]: We can't get page from context which is a path to structure element in structure tree. In this case, `page` will always be `-1`. So, we don't need to pass it to `findAllMcid` function

Comment (Resip10) [reply src/components/layouts/pages/inspect/pdfDocument/PdfDocument.js:94]: Removed useless page
