### PR TITLE
Fixes for #77, #79 and #61 issues

### LINKED ISSUE #61: [FE - inspect page] Improve displaying rules with the same path
File: 
[7.2-t01_fail.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4711262/7.2-t01_fail.pdf)
The same path of different rules are displayed in summary tree
**Actual result**: When you try to select element  it always to redirect you to first rules
img1

### LINKED ISSUE #77: [FE - Summary-tree] Align information in summary-tree
[7.2-t30-fail-a.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4734535/7.2-t30-fail-a.pdf)
img

### LINKED ISSUE #79: [FE] - Fix elements selection
[7.1-t05-fail-c.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4736128/7.1-t05-fail-c.pdf)
Make selection of elements with empty value in Rolemap key is possible as in Acrobat.

### PR DESCRIPTION
**Pull request by Resip10**
closes #77 
closes #79 
closes #61 
Adjusted check key with rule index;
Fixed cleaning of 0-index page

### CODE REVIEW

File: src/components/layouts/pages/inspect/pdfDocument/PdfDocument.js [hunk 1]
```diff
@@ -120,7 +120,7 @@ class PdfDocument extends React.PureComponent {
                 ? this.state.errorsRects[prevProps.selectedCheck]?.pageIndex
                 : this.state.mapOfErrors[this.props.selectedCheck]?.pageIndex;
 
-            if (prevPage) {
+            if (!_.isNaN(prevPage)) {
```
Comment (KateOrient) [inline src/components/layouts/pages/inspect/pdfDocument/PdfDocument.js:123]: This check doesn't make sence. Possible invalid values for `prevPage` are `undefined` and `-1` , but not `NaN`

File: src/components/layouts/pages/inspect/tree/Tree.js [hunk 2]
```diff
@@ -53,12 +53,13 @@ function Tree({ ruleSummaries, selectedCheck, setSelectedCheck, errorsMap }) {
     useEffect(
         useCallback(() => {
             if (selectedCheck) {
-                let rule = ruleSummaries.findIndex(rule => rule.checks.find(check => check.context === selectedCheck));
-                if (rule !== -1 && rule !== expandedRule) {
-                    setExpandedRule(rule);
+                let [ruleIndex] = selectedCheck.split(':');
+                ruleIndex = parseInt(ruleIndex);
+                if (ruleIndex !== expandedRule) {
+                    setExpandedRule(parseInt(ruleIndex));
```
Comment (KateOrient) [inline src/components/layouts/pages/inspect/tree/Tree.js:59]: Dublicated `parseInt` call for `ruleIndex`
