### PR TITLE
Bug-fixing: auto scroll, #89, #86

### LINKED ISSUE #86: [FE - Inspect Document] Image of document is completely darked after moving pointer
[Det is Berlin_rPDF_example_2017-02-27.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4751760/Det.is.Berlin_rPDF_example_2017-02-27.pdf)

1. Inspect attached PDF file on WCAG 2.1 (All) profile
2. Select image in "inspect-document area"
3. Moving pointer on next image

**Actual result:** Image is darked
dark
**Expected result:** Image is not darked

### LINKED ISSUE #89: [FE - Inspect Page] Selection elements problem due to uncaught typeError
[forms.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4751961/forms.pdf)

1. Upload attached PDF
2. Inspect it
3. Select elements in "inspect-document" section

**Actual result:** Cannot select elements. 
inspect
**Expected result:** Form elements may be selected

### PR DESCRIPTION
**Pull request by Resip10**
Part of #54 : Added auto scroll on select from pdf check
closes #89 : Fixed error of annotations on first page
closes #86 : Fixed canvas redrawing on mouseMove event

### CODE REVIEW

File: src/components/layouts/pages/inspect/tree/Tree.js [hunk 1]
```diff
@@ -146,20 +146,43 @@ function CheckList({ checks, selectedCheck, onCheckClick, errorsMap, ruleIndex }
...
+    }, [onClick]);
+    const listItem = useRef();
+    useEffect(() => {
+        if (selected && !disableAutoScroll) {
+            // To be sure that list expanded before auto scroll
+            setTimeout(() => listItem.current.scrollIntoView({ block: 'center' }), 0);
+        } else {
+            setDisableAutoScroll(false);
+        }
+    }, [selected]); // don't put disableAutoScroll in deps, it will make always to autoscroll
```
Comment (KateOrient) [inline src/components/layouts/pages/inspect/tree/Tree.js:177]: It's possible to avoid console warnings by wrapping function inside `useEffect` into `useCallback`
